name: witec
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - jupyterlab
  - jupytext
  - matplotlib=3.7.*
  - numpy
  - pandas
  - pre-commit=3.*
  - pytest
  - pyyaml
  - scienceplots
