name: witec
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - scifireaders
  - h5py
  - ipympl
  # - jupyterlab
  # - jupytext
  - matplotlib
  - numpy
  - pandas
  - pre-commit
  - pycroscopy
  - pytest
  - pyUSID
  - pyNSID
  - pyyaml
  - scienceplots
  - pip:
    # - sidpy
